# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/explRL',
                'doc_host': 'https://ChuntaoDan.github.io',
                'git_url': 'https://github.com/ChuntaoDan/explRL',
                'lib_path': 'explRL'},
  'syms': { 'explRL.core': { 'explRL.core.loadAgent': ('core.html#loadagent', 'explRL/core.py'),
                             'explRL.core.loadEnv': ('core.html#loadenv', 'explRL/core.py')}}}
