# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/agents.ipynb.

# %% auto 0
__all__ = ['Policy', 'RL', 'Agent']

# %% ../nbs/agents.ipynb 3
class Policy():
    '''This Policy Class specifies a general architecture. '''
    def __init__(self):
        self.heading = None
        self.actions = None
        self.act = None
        
    def sampleAction(self):
        pass
        return self.act

# %% ../nbs/agents.ipynb 4
class RL():
    '''This RL Class performs reinforcement learning: after taking an action, update parameters 
    based on feedback from the environment.
    '''
    def __init__(self):
        self.policy = None
        self.actions = None
        
    def chooseAction(self):
        pass
        return self.act
    
    def updateParams(self):
        pass
        return self.params

# %% ../nbs/agents.ipynb 5
class Agent:
    '''This Agent Class specifies agents using a defined policy and reinforcement learning algorithm. '''
    def __init__(self):
        self.heading = None
        self.actions = None
        self.act = None
        
    def chooseAction(self):
        pass
        return self.act
