# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/agents.ipynb.

# %% auto 0
__all__ = ['Agent']

# %% ../nbs/agents.ipynb 3
class Agent:
    '''This Agent Class specifies agents  '''
    def __init__(self):
        self.location = None
        self.actons = None
        self.act = None
        self.energy = None
        
    def chooseAction(self):
        pass
        return self.act
