# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['loadAgent', 'loadEnv']

# %% ../nbs/00_core.ipynb 3
def loadAgent(): 
    '''This function loads an agent object from a specified Agent Class. '''
    agent = None
    return agent

# %% ../nbs/00_core.ipynb 4
def loadEnv(): 
    '''This function loads an env object from a specified Environment Class. '''
    env = None
    return env
